import { useState } from 'react';
import type { StandupResult } from '../data/standup-data';
import StandupCard from './StandupCard';

interface StandupOutputProps {
  result: StandupResult;
  onRegenerate: () => void;
}

export default function StandupOutput({ result, onRegenerate }: StandupOutputProps) {
  const [copied, setCopied] = useState(false);

  function copyToClipboard() {
    const text = `Yesterday: ${result.yesterday}\nToday: ${result.today}\nBlockers: ${result.blocker}`;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const cards = [
    { label: 'YESTERDAY', value: result.yesterday, color: '#00ffff' },
    { label: 'TODAY', value: result.today, color: '#00ff41' },
    { label: 'BLOCKERS', value: result.blocker, color: '#ff0000' },
  ];

  return (
    <div className="standup-card">
      <div className="text-center mb-6">
        <div className="text-5xl">{result.mood.emoji}</div>
        <div
          className="text-[0.6rem] tracking-[4px] mt-1"
          style={{ color: result.mood.color }}
        >
          TODAY'S MOOD: {result.mood.label}
        </div>
      </div>

      {cards.map((item) => (
        <StandupCard
          key={item.label}
          label={item.label}
          value={item.value}
          color={item.color}
        />
      ))}

      <div className="border border-cyan-900/20 bg-cyan-500/[0.02] p-4 mb-4 text-[0.7rem] leading-8 text-cyan-400/50">
        <div className="text-[0.58rem] tracking-[3px] text-cyan-400/25 mb-2">
          PASTE-READY FORMAT:
        </div>
        <div>
          <span className="text-base mr-1">{'\u{1F4C5}'}</span>
          <strong className="text-cyan-400">Yesterday:</strong> {result.yesterday}
        </div>
        <div>
          <span className="text-base mr-1">{'\u{1F3AF}'}</span>
          <strong className="text-green-400">Today:</strong> {result.today}
        </div>
        <div>
          <span className="text-base mr-1">{'\u{1F6A7}'}</span>
          <strong className="text-red-500">Blockers:</strong> {result.blocker}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-2 mb-6">
        <button
          onClick={copyToClipboard}
          className="cbtn bg-transparent border border-cyan-400/25 font-mono text-[0.68rem] py-2.5 px-3 cursor-pointer tracking-[2px] transition-all"
          style={{ color: copied ? '#00ff41' : 'rgba(0,255,255,0.53)' }}
        >
          {copied ? '\u2713 COPIED' : 'COPY TO SLACK'}
        </button>
        <button
          onClick={onRegenerate}
          className="cbtn bg-transparent border border-cyan-400/25 text-cyan-400/50 font-mono text-[0.68rem] py-2.5 px-3 cursor-pointer tracking-[2px] transition-all"
        >
          REGENERATE
        </button>
      </div>

      <div className="border border-orange-400/10 bg-orange-400/[0.03] p-3 text-[0.6rem] text-orange-400/40 leading-7">
        {'\u26A0'} DISCLAIMER: This standup was generated by an algorithm with 0 understanding of your actual work.
        It is indistinguishable from a real standup. This is not our fault. This is agile's fault.
      </div>
    </div>
  );
}
